### PR TITLE
Eye detection

### PR DESCRIPTION
**Pull request by cor1234**
I use HaarCascade to detect eye in video frame and later it will be helpful to control media player using eye blinding

### CODE REVIEW

**Review by AmitSingh12345678 — APPROVED** [review]
Looks good to me.

**Review by PK-cod3ch3mist — APPROVED** [review]
Haven't run the code but the logic looks fine.

**Comment by hailer24** [comment]
looks good to me as well

**Review by hailer24 — APPROVED** [review]

**Review by hailer24 — CHANGES_REQUESTED** [review]
haar cascade is not that reliable so have a discussion with others about usage of mediapipe or dlib over haar cascade

**Review by Sanchit-sk — CHANGES_REQUESTED** [review]
The code is good but my eyes are not being detected many a times and even the face is not being detected in some instances. Seems like a reliability issue with haar-cascade method.
I even enhanced the image using histogram equalization (contrast enhancement) but still the issue persists. Can we optimize it or try some other alternative?

**Comment by hailer24** [comment]
@Sanchit-sk I am closing this pull request for now

**Pull request closed without merging**
